spring:
  datasource:
     url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&charset=utf8mb4&autoReconnect=true
     username: root
     password: 123456
     driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
     properties:
        hibernate:
         hbm2ddl:
            auto: update
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
     show-sql: true